const politicalParties = {
  70: { initials: 'AVANTE', name: 'Avante' },
  27: { initials: 'DC', name: 'Democracia Cristã' },
  25: { initials: 'DEM', name: 'Democratas' },
  15: { initials: 'MDB', name: 'Movimento Democrático Brasileiro' },
  21: { initials: 'PCB', name: 'Partido Comunista Brasileiro' },
  65: { initials: 'PCdoB', name: 'Partido Comunista do Brasil' },
  29: { initials: 'PCO', name: 'Partido da Causa Operária' },
  33: { initials: 'PMN', name: 'Partido da Mobilização Nacional' },
  35: { initials: 'PMB', name: 'Partido da Mulher Brasileira[59]' },
  22: { initials: 'PR', name: 'Partido da República' },
  45: { initials: 'PSDB', name: 'Partido da Social Democracia Brasileira' },
  12: { initials: 'PDT', name: 'Partido Democrático Trabalhista' },
  13: { initials: 'PT', name: 'Partido dos Trabalhadores' },
  31: { initials: 'PHS', name: 'Partido Humanista da Solidariedade' },
  30: { initials: 'NOVO', name: 'Partido Novo[65]' },
  54: { initials: 'PPL', name: 'Partido Pátria Livre' },
  23: { initials: 'PPS', name: 'Partido Popular Socialista' },
  11: { initials: 'PP', name: 'Partido Progressista' },
  28: { initials: 'PRTB', name: 'Partido Renovador Trabalhista Brasileiro' },
  10: { initials: 'PRB', name: 'Partido Republicano Brasileiro' },
  90: { initials: 'PROS', name: 'Partido Republicano da Ordem Social' },
  44: { initials: 'PRP', name: 'Partido Republicano Progressista' },
  20: { initials: 'PSC', name: 'Partido Social Cristão' },
  55: { initials: 'PSD', name: 'Partido Social Democrático' },
  17: { initials: 'PSL', name: 'Partido Social Liberal' },
  50: { initials: 'PSOL', name: 'Partido Socialismo e Liberdade' },
  40: { initials: 'PSB', name: 'Partido Socialista Brasileiro' },
  16: { initials: 'PSTU', name: 'Partido Socialista dos Trabalhadores Unificado' },
  14: { initials: 'PTB', name: 'Partido Trabalhista Brasileiro' },
  36: { initials: 'PTC', name: 'Partido Trabalhista Cristão' },
  43: { initials: 'PV', name: 'Partido Verde' },
  51: { initials: 'PATRI', name: 'Patriota' },
  19: { initials: 'PODE', name: 'Podemos' },
  18: { initials: 'REDE', name: 'Rede Sustentabilidade' },
  77: { initials: 'SD', name: 'Solidariedade' }
};

export default politicalParties;
