import React, { PureComponent } from 'react';
import firebase from 'firebase/app';

class SignupForm extends PureComponent {
  handleSubmit = event => {
    event.preventDefault();

    const email = event.target.email.value;
    const password = event.target.password.value;

    firebase
      .auth()
      .createUserWithEmailAndPassword(email, password)
      .catch(console.log);
  };

  render() {
    return (
      <form onSubmit={this.handleSubmit}>
        <div>
          <button type="button" onClick={() => this.props.showLoginPage(true)}>
            Entrar
          </button>
          <button type="button" onClick={() => this.props.showLoginPage(false)}>
            Cadastrar
          </button>
        </div>

        <div className="form-group">
          <label htmlFor="name">Nome</label>
          <input type="text" name="name" id="name" />
        </div>

        <div className="form-group">
          <label htmlFor="email">E-mail</label>
          <input type="text" name="email" id="email" />
        </div>

        <div className="form-group">
          <label htmlFor="password">Senha</label>
          <input type="password" name="password" id="password" />
        </div>

        <div className="form-group">
          <label htmlFor="cidade">Cidade</label>
          <select name="cidade" id="cidade">
            <option value="Adamantina">Adamantina</option>
            <option value="Adolfo">Adolfo</option>
            <option value="Aguai">Aguai</option>
            <option value="Aguas da Prata">Aguas da Prata</option>
            <option value="Aguas de Lindoia">Aguas de Lindoia</option>
            <option value="Aguas de Santa Barbara">Aguas de Santa Barbara</option>
            <option value="Aguas de Sao Pedro">Aguas de Sao Pedro</option>
            <option value="Agudos">Agudos</option>
            <option value="Alambari">Alambari</option>
            <option value="Alfredo Marcondes">Alfredo Marcondes</option>
            <option value="Altair">Altair</option>
            <option value="Altinopolis">Altinopolis</option>
            <option value="Alto Alegre">Alto Alegre</option>
            <option value="Aluminio">Aluminio</option>
            <option value="Alvares Florence">Alvares Florence</option>
            <option value="Alvares Machado">Alvares Machado</option>
            <option value="Alvaro de Carvalho">Alvaro de Carvalho</option>
            <option value="Alvinlandia">Alvinlandia</option>
            <option value="Americana">Americana</option>
            <option value="Americo Brasiliense">Americo Brasiliense</option>
            <option value="Americo de Campos">Americo de Campos</option>
            <option value="Amparo">Amparo</option>
            <option value="Analandia">Analandia</option>
            <option value="Andradina">Andradina</option>
            <option value="Angatuba">Angatuba</option>
            <option value="Anhembi">Anhembi</option>
            <option value="Anhumas">Anhumas</option>
            <option value="Aparecida d'Oeste">Aparecida d'Oeste</option>
            <option value="Aparecida">Aparecida</option>
            <option value="Apiai">Apiai</option>
            <option value="Aracariguama">Aracariguama</option>
            <option value="Aracatuba">Aracatuba</option>
            <option value="Aracoiaba da Serra">Aracoiaba da Serra</option>
            <option value="Aramina">Aramina</option>
            <option value="Arandu">Arandu</option>
            <option value="Arapei">Arapei</option>
            <option value="Araraquara">Araraquara</option>
            <option value="Araras">Araras</option>
            <option value="Arco-Iris">Arco-Iris</option>
            <option value="Arealva">Arealva</option>
            <option value="Areias">Areias</option>
            <option value="Areiopolis">Areiopolis</option>
            <option value="Ariranha">Ariranha</option>
            <option value="Artur Nogueira">Artur Nogueira</option>
            <option value="Aruja">Aruja</option>
            <option value="Aspasia">Aspasia</option>
            <option value="Assis">Assis</option>
            <option value="Atibaia">Atibaia</option>
            <option value="Auriflama">Auriflama</option>
            <option value="Avai">Avai</option>
            <option value="Avanhandava">Avanhandava</option>
            <option value="Avare">Avare</option>
            <option value="Bady Bassitt">Bady Bassitt</option>
            <option value="Balbinos">Balbinos</option>
            <option value="Balsamo">Balsamo</option>
            <option value="Bananal">Bananal</option>
            <option value="Barao de Antonina">Barao de Antonina</option>
            <option value="Barbosa">Barbosa</option>
            <option value="Bariri">Bariri</option>
            <option value="Barra Bonita">Barra Bonita</option>
            <option value="Barra do Chapeu">Barra do Chapeu</option>
            <option value="Barra do Turvo">Barra do Turvo</option>
            <option value="Barretos">Barretos</option>
            <option value="Barrinha">Barrinha</option>
            <option value="Barueri">Barueri</option>
            <option value="Bastos">Bastos</option>
            <option value="Batatais">Batatais</option>
            <option value="Bauru">Bauru</option>
            <option value="Bebedouro">Bebedouro</option>
            <option value="Bento de Abreu">Bento de Abreu</option>
            <option value="Bernardino de Campos">Bernardino de Campos</option>
            <option value="Bertioga">Bertioga</option>
            <option value="Bilac">Bilac</option>
            <option value="Birigui">Birigui</option>
            <option value="Biritiba-Mirim">Biritiba-Mirim</option>
            <option value="Boa Esperanca do Sul">Boa Esperanca do Sul</option>
            <option value="Bocaina">Bocaina</option>
            <option value="Bofete">Bofete</option>
            <option value="Boituva">Boituva</option>
            <option value="Bom Jesus dos Perdoes">Bom Jesus dos Perdoes</option>
            <option value="Bom Sucesso de Itarare">Bom Sucesso de Itarare</option>
            <option value="Bora">Bora</option>
            <option value="Boraceia">Boraceia</option>
            <option value="Borborema">Borborema</option>
            <option value="Borebi">Borebi</option>
            <option value="Botucatu">Botucatu</option>
            <option value="Braganca Paulista">Braganca Paulista</option>
            <option value="Brauna">Brauna</option>
            <option value="Brejo Alegre">Brejo Alegre</option>
            <option value="Brodosqui">Brodosqui</option>
            <option value="Brotas">Brotas</option>
            <option value="Buri">Buri</option>
            <option value="Buritama">Buritama</option>
            <option value="Buritizal">Buritizal</option>
            <option value="Cabralia Paulista">Cabralia Paulista</option>
            <option value="Cabreuva">Cabreuva</option>
            <option value="Cacapava">Cacapava</option>
            <option value="Cachoeira Paulista">Cachoeira Paulista</option>
            <option value="Caconde">Caconde</option>
            <option value="Cafelandia">Cafelandia</option>
            <option value="Caiabu">Caiabu</option>
            <option value="Caieiras">Caieiras</option>
            <option value="Caiua">Caiua</option>
            <option value="Cajamar">Cajamar</option>
            <option value="Cajati">Cajati</option>
            <option value="Cajobi">Cajobi</option>
            <option value="Cajuru">Cajuru</option>
            <option value="Campina do Monte Alegre">Campina do Monte Alegre</option>
            <option value="Campinas">Campinas</option>
            <option value="Campo Limpo Paulista">Campo Limpo Paulista</option>
            <option value="Campos Novos Paulista">Campos Novos Paulista</option>
            <option value="Campos do Jordao">Campos do Jordao</option>
            <option value="Cananeia">Cananeia</option>
            <option value="Canas">Canas</option>
            <option value="Candido Mota">Candido Mota</option>
            <option value="Candido Rodrigues">Candido Rodrigues</option>
            <option value="Canitar">Canitar</option>
            <option value="Capao Bonito">Capao Bonito</option>
            <option value="Capela do Alto">Capela do Alto</option>
            <option value="Capivari">Capivari</option>
            <option value="Caraguatatuba">Caraguatatuba</option>
            <option value="Carapicuiba">Carapicuiba</option>
            <option value="Cardoso">Cardoso</option>
            <option value="Casa Branca">Casa Branca</option>
            <option value="Cassia dos Coqueiros">Cassia dos Coqueiros</option>
            <option value="Castilho">Castilho</option>
            <option value="Catanduva">Catanduva</option>
            <option value="Catigua">Catigua</option>
            <option value="Cedral">Cedral</option>
            <option value="Cerqueira Cesar">Cerqueira Cesar</option>
            <option value="Cerquilho">Cerquilho</option>
            <option value="Cesario Lange">Cesario Lange</option>
            <option value="Charqueada">Charqueada</option>
            <option value="Chavantes">Chavantes</option>
            <option value="Clementina">Clementina</option>
            <option value="Colina">Colina</option>
            <option value="Colombia">Colombia</option>
            <option value="Conchal">Conchal</option>
            <option value="Conchas">Conchas</option>
            <option value="Cordeiropolis">Cordeiropolis</option>
            <option value="Coroados">Coroados</option>
            <option value="Coronel Macedo">Coronel Macedo</option>
            <option value="Corumbatai">Corumbatai</option>
            <option value="Cosmopolis">Cosmopolis</option>
            <option value="Cosmorama">Cosmorama</option>
            <option value="Cotia">Cotia</option>
            <option value="Cravinhos">Cravinhos</option>
            <option value="Cristais Paulista">Cristais Paulista</option>
            <option value="Cruzalia">Cruzalia</option>
            <option value="Cruzeiro">Cruzeiro</option>
            <option value="Cubatao">Cubatao</option>
            <option value="Cunha">Cunha</option>
            <option value="Descalvado">Descalvado</option>
            <option value="Diadema">Diadema</option>
            <option value="Dirce Reis">Dirce Reis</option>
            <option value="Divinolandia">Divinolandia</option>
            <option value="Dobrada">Dobrada</option>
            <option value="Dois Corregos">Dois Corregos</option>
            <option value="Dolcinopolis">Dolcinopolis</option>
            <option value="Dourado">Dourado</option>
            <option value="Dracena">Dracena</option>
            <option value="Duartina">Duartina</option>
            <option value="Dumont">Dumont</option>
            <option value="Echapora">Echapora</option>
            <option value="Eldorado">Eldorado</option>
            <option value="Elias Fausto">Elias Fausto</option>
            <option value="Elisiario">Elisiario</option>
            <option value="Embauba">Embauba</option>
            <option value="Embu">Embu</option>
            <option value="Embu-Guacu">Embu-Guacu</option>
            <option value="Emilianopolis">Emilianopolis</option>
            <option value="Engenheiro Coelho">Engenheiro Coelho</option>
            <option value="Espirito Santo do Pinhal">Espirito Santo do Pinhal</option>
            <option value="Espirito Santo do Turvo">Espirito Santo do Turvo</option>
            <option value="Estiva Gerbi">Estiva Gerbi</option>
            <option value="Estrela d'Oeste">Estrela d'Oeste</option>
            <option value="Estrela do Norte">Estrela do Norte</option>
            <option value="Euclides da Cunha Paulista">Euclides da Cunha Paulista</option>
            <option value="Fartura">Fartura</option>
            <option value="Fernando Prestes">Fernando Prestes</option>
            <option value="Fernandopolis">Fernandopolis</option>
            <option value="Fernao">Fernao</option>
            <option value="Ferraz de Vasconcelos">Ferraz de Vasconcelos</option>
            <option value="Flora Rica">Flora Rica</option>
            <option value="Floreal">Floreal</option>
            <option value="Florida Paulista">Florida Paulista</option>
            <option value="Florinia">Florinia</option>
            <option value="Franca">Franca</option>
            <option value="Francisco Morato">Francisco Morato</option>
            <option value="Franco da Rocha">Franco da Rocha</option>
            <option value="Gabriel Monteiro">Gabriel Monteiro</option>
            <option value="Galia">Galia</option>
            <option value="Garca">Garca</option>
            <option value="Gastao Vidigal">Gastao Vidigal</option>
            <option value="Gaviao Peixoto">Gaviao Peixoto</option>
            <option value="General Salgado">General Salgado</option>
            <option value="Getulina">Getulina</option>
            <option value="Glicerio">Glicerio</option>
            <option value="Guaicara">Guaicara</option>
            <option value="Guaimbe">Guaimbe</option>
            <option value="Guaira">Guaira</option>
            <option value="Guapiacu">Guapiacu</option>
            <option value="Guapiara">Guapiara</option>
            <option value="Guara">Guara</option>
            <option value="Guaracai">Guaracai</option>
            <option value="Guaraci">Guaraci</option>
            <option value="Guarani d'Oeste">Guarani d'Oeste</option>
            <option value="Guaranta">Guaranta</option>
            <option value="Guararapes">Guararapes</option>
            <option value="Guararema">Guararema</option>
            <option value="Guaratingueta">Guaratingueta</option>
            <option value="Guarei">Guarei</option>
            <option value="Guariba">Guariba</option>
            <option value="Guaruja">Guaruja</option>
            <option value="Guarulhos">Guarulhos</option>
            <option value="Guatapara">Guatapara</option>
            <option value="Guzolandia">Guzolandia</option>
            <option value="Herculandia">Herculandia</option>
            <option value="Holambra">Holambra</option>
            <option value="Hortolandia">Hortolandia</option>
            <option value="Iacanga">Iacanga</option>
            <option value="Iacri">Iacri</option>
            <option value="Iaras">Iaras</option>
            <option value="Ibate">Ibate</option>
            <option value="Ibira">Ibira</option>
            <option value="Ibirarema">Ibirarema</option>
            <option value="Ibitinga">Ibitinga</option>
            <option value="Ibiuna">Ibiuna</option>
            <option value="Icem">Icem</option>
            <option value="Iepe">Iepe</option>
            <option value="Igaracu do Tiete">Igaracu do Tiete</option>
            <option value="Igarapava">Igarapava</option>
            <option value="Igarata">Igarata</option>
            <option value="Iguape">Iguape</option>
            <option value="Ilha Comprida">Ilha Comprida</option>
            <option value="Ilha Solteira">Ilha Solteira</option>
            <option value="Ilhabela">Ilhabela</option>
            <option value="Indaiatuba">Indaiatuba</option>
            <option value="Indiana">Indiana</option>
            <option value="Indiapora">Indiapora</option>
            <option value="Inubia Paulista">Inubia Paulista</option>
            <option value="Ipaucu">Ipaucu</option>
            <option value="Ipero">Ipero</option>
            <option value="Ipeuna">Ipeuna</option>
            <option value="Ipigua">Ipigua</option>
            <option value="Iporanga">Iporanga</option>
            <option value="Ipua">Ipua</option>
            <option value="Iracemapolis">Iracemapolis</option>
            <option value="Irapua">Irapua</option>
            <option value="Irapuru">Irapuru</option>
            <option value="Itabera">Itabera</option>
            <option value="Itai">Itai</option>
            <option value="Itajobi">Itajobi</option>
            <option value="Itaju">Itaju</option>
            <option value="Itanhaem">Itanhaem</option>
            <option value="Itaoca">Itaoca</option>
            <option value="Itapecerica da Serra">Itapecerica da Serra</option>
            <option value="Itapetininga">Itapetininga</option>
            <option value="Itapeva">Itapeva</option>
            <option value="Itapevi">Itapevi</option>
            <option value="Itapira">Itapira</option>
            <option value="Itapirapua Paulista">Itapirapua Paulista</option>
            <option value="Itapolis">Itapolis</option>
            <option value="Itaporanga">Itaporanga</option>
            <option value="Itapui">Itapui</option>
            <option value="Itapura">Itapura</option>
            <option value="Itaquaquecetuba">Itaquaquecetuba</option>
            <option value="Itarare">Itarare</option>
            <option value="Itariri">Itariri</option>
            <option value="Itatiba">Itatiba</option>
            <option value="Itatinga">Itatinga</option>
            <option value="Itirapina">Itirapina</option>
            <option value="Itirapua">Itirapua</option>
            <option value="Itobi">Itobi</option>
            <option value="Itu">Itu</option>
            <option value="Itupeva">Itupeva</option>
            <option value="Ituverava">Ituverava</option>
            <option value="Jaborandi">Jaborandi</option>
            <option value="Jaboticabal">Jaboticabal</option>
            <option value="Jacarei">Jacarei</option>
            <option value="Jaci">Jaci</option>
            <option value="Jacupiranga">Jacupiranga</option>
            <option value="Jaguariuna">Jaguariuna</option>
            <option value="Jales">Jales</option>
            <option value="Jambeiro">Jambeiro</option>
            <option value="Jandira">Jandira</option>
            <option value="Jardinopolis">Jardinopolis</option>
            <option value="Jarinu">Jarinu</option>
            <option value="Jau">Jau</option>
            <option value="Jeriquara">Jeriquara</option>
            <option value="Joanopolis">Joanopolis</option>
            <option value="Joao Ramalho">Joao Ramalho</option>
            <option value="Jose Bonifacio">Jose Bonifacio</option>
            <option value="Julio Mesquita">Julio Mesquita</option>
            <option value="Jumirim">Jumirim</option>
            <option value="Jundiai">Jundiai</option>
            <option value="Junqueiropolis">Junqueiropolis</option>
            <option value="Juquia">Juquia</option>
            <option value="Juquitiba">Juquitiba</option>
            <option value="Lagoinha">Lagoinha</option>
            <option value="Laranjal Paulista">Laranjal Paulista</option>
            <option value="Lavinia">Lavinia</option>
            <option value="Lavrinhas">Lavrinhas</option>
            <option value="Leme">Leme</option>
            <option value="Lencois Paulista">Lencois Paulista</option>
            <option value="Limeira">Limeira</option>
            <option value="Lindoia">Lindoia</option>
            <option value="Lins">Lins</option>
            <option value="Lorena">Lorena</option>
            <option value="Lourdes">Lourdes</option>
            <option value="Louveira">Louveira</option>
            <option value="Lucelia">Lucelia</option>
            <option value="Lucianopolis">Lucianopolis</option>
            <option value="Luis Antonio">Luis Antonio</option>
            <option value="Luiziania">Luiziania</option>
            <option value="Lupercio">Lupercio</option>
            <option value="Lutecia">Lutecia</option>
            <option value="Macatuba">Macatuba</option>
            <option value="Macaubal">Macaubal</option>
            <option value="Macedonia">Macedonia</option>
            <option value="Magda">Magda</option>
            <option value="Mairinque">Mairinque</option>
            <option value="Mairipora">Mairipora</option>
            <option value="Manduri">Manduri</option>
            <option value="Maraba Paulista">Maraba Paulista</option>
            <option value="Maracai">Maracai</option>
            <option value="Marapoama">Marapoama</option>
            <option value="Mariapolis">Mariapolis</option>
            <option value="Marilia">Marilia</option>
            <option value="Marinopolis">Marinopolis</option>
            <option value="Martinopolis">Martinopolis</option>
            <option value="Matao">Matao</option>
            <option value="Maua">Maua</option>
            <option value="Mendonca">Mendonca</option>
            <option value="Meridiano">Meridiano</option>
            <option value="Mesopolis">Mesopolis</option>
            <option value="Miguelopolis">Miguelopolis</option>
            <option value="Mineiros do Tiete">Mineiros do Tiete</option>
            <option value="Mira Estrela">Mira Estrela</option>
            <option value="Miracatu">Miracatu</option>
            <option value="Mirandopolis">Mirandopolis</option>
            <option value="Mirante do Paranapanema">Mirante do Paranapanema</option>
            <option value="Mirassol">Mirassol</option>
            <option value="Mirassolandia">Mirassolandia</option>
            <option value="Mococa">Mococa</option>
            <option value="Mogi Guacu">Mogi Guacu</option>
            <option value="Moji das Cruzes">Moji das Cruzes</option>
            <option value="Moji-Mirim">Moji-Mirim</option>
            <option value="Mombuca">Mombuca</option>
            <option value="Moncoes">Moncoes</option>
            <option value="Mongagua">Mongagua</option>
            <option value="Monte Alegre do Sul">Monte Alegre do Sul</option>
            <option value="Monte Alto">Monte Alto</option>
            <option value="Monte Aprazivel">Monte Aprazivel</option>
            <option value="Monte Azul Paulista">Monte Azul Paulista</option>
            <option value="Monte Castelo">Monte Castelo</option>
            <option value="Monte Mor">Monte Mor</option>
            <option value="Monteiro Lobato">Monteiro Lobato</option>
            <option value="Morro Agudo">Morro Agudo</option>
            <option value="Morungaba">Morungaba</option>
            <option value="Motuca">Motuca</option>
            <option value="Murutinga do Sul">Murutinga do Sul</option>
            <option value="Nantes">Nantes</option>
            <option value="Narandiba">Narandiba</option>
            <option value="Natividade da Serra">Natividade da Serra</option>
            <option value="Nazare Paulista">Nazare Paulista</option>
            <option value="Neves Paulista">Neves Paulista</option>
            <option value="Nhandeara">Nhandeara</option>
            <option value="Nipoa">Nipoa</option>
            <option value="Nova Alianca">Nova Alianca</option>
            <option value="Nova Campina">Nova Campina</option>
            <option value="Nova Canaa Paulista">Nova Canaa Paulista</option>
            <option value="Nova Castilho">Nova Castilho</option>
            <option value="Nova Europa">Nova Europa</option>
            <option value="Nova Granada">Nova Granada</option>
            <option value="Nova Guataporanga">Nova Guataporanga</option>
            <option value="Nova Independencia">Nova Independencia</option>
            <option value="Nova Luzitania">Nova Luzitania</option>
            <option value="Nova Odessa">Nova Odessa</option>
            <option value="Novais">Novais</option>
            <option value="Novo Horizonte">Novo Horizonte</option>
            <option value="Nuporanga">Nuporanga</option>
            <option value="Ocaucu">Ocaucu</option>
            <option value="Oleo">Oleo</option>
            <option value="Olimpia">Olimpia</option>
            <option value="Onda Verde">Onda Verde</option>
            <option value="Oriente">Oriente</option>
            <option value="Orindiuva">Orindiuva</option>
            <option value="Orlandia">Orlandia</option>
            <option value="Osasco">Osasco</option>
            <option value="Oscar Bressane">Oscar Bressane</option>
            <option value="Osvaldo Cruz">Osvaldo Cruz</option>
            <option value="Ourinhos">Ourinhos</option>
            <option value="Ouro Verde">Ouro Verde</option>
            <option value="Ouroeste">Ouroeste</option>
            <option value="Pacaembu">Pacaembu</option>
            <option value="Palestina">Palestina</option>
            <option value="Palmares Paulista">Palmares Paulista</option>
            <option value="Palmeira d'Oeste">Palmeira d'Oeste</option>
            <option value="Palmital">Palmital</option>
            <option value="Panorama">Panorama</option>
            <option value="Paraguacu Paulista">Paraguacu Paulista</option>
            <option value="Paraibuna">Paraibuna</option>
            <option value="Paraiso">Paraiso</option>
            <option value="Paranapanema">Paranapanema</option>
            <option value="Paranapua">Paranapua</option>
            <option value="Parapua">Parapua</option>
            <option value="Pardinho">Pardinho</option>
            <option value="Pariquera-Acu">Pariquera-Acu</option>
            <option value="Parisi">Parisi</option>
            <option value="Patrocinio Paulista">Patrocinio Paulista</option>
            <option value="Pauliceia">Pauliceia</option>
            <option value="Paulinia">Paulinia</option>
            <option value="Paulistania">Paulistania</option>
            <option value="Paulo de Faria">Paulo de Faria</option>
            <option value="Pederneiras">Pederneiras</option>
            <option value="Pedra Bela">Pedra Bela</option>
            <option value="Pedranopolis">Pedranopolis</option>
            <option value="Pedregulho">Pedregulho</option>
            <option value="Pedreira">Pedreira</option>
            <option value="Pedrinhas Paulista">Pedrinhas Paulista</option>
            <option value="Pedro de Toledo">Pedro de Toledo</option>
            <option value="Penapolis">Penapolis</option>
            <option value="Pereira Barreto">Pereira Barreto</option>
            <option value="Pereiras">Pereiras</option>
            <option value="Peruibe">Peruibe</option>
            <option value="Piacatu">Piacatu</option>
            <option value="Piedade">Piedade</option>
            <option value="Pilar do Sul">Pilar do Sul</option>
            <option value="Pindamonhangaba">Pindamonhangaba</option>
            <option value="Pindorama">Pindorama</option>
            <option value="Pinhalzinho">Pinhalzinho</option>
            <option value="Piquerobi">Piquerobi</option>
            <option value="Piquete">Piquete</option>
            <option value="Piracaia">Piracaia</option>
            <option value="Piracicaba">Piracicaba</option>
            <option value="Piraju">Piraju</option>
            <option value="Pirajui">Pirajui</option>
            <option value="Pirangi">Pirangi</option>
            <option value="Pirapora do Bom Jesus">Pirapora do Bom Jesus</option>
            <option value="Pirapozinho">Pirapozinho</option>
            <option value="Pirassununga">Pirassununga</option>
            <option value="Piratininga">Piratininga</option>
            <option value="Pitangueiras">Pitangueiras</option>
            <option value="Planalto">Planalto</option>
            <option value="Platina">Platina</option>
            <option value="Poa">Poa</option>
            <option value="Poloni">Poloni</option>
            <option value="Pompeia">Pompeia</option>
            <option value="Pongai">Pongai</option>
            <option value="Pontal">Pontal</option>
            <option value="Pontalinda">Pontalinda</option>
            <option value="Pontes Gestal">Pontes Gestal</option>
            <option value="Populina">Populina</option>
            <option value="Porangaba">Porangaba</option>
            <option value="Porto Feliz">Porto Feliz</option>
            <option value="Porto Ferreira">Porto Ferreira</option>
            <option value="Potim">Potim</option>
            <option value="Potirendaba">Potirendaba</option>
            <option value="Pracinha">Pracinha</option>
            <option value="Pradopolis">Pradopolis</option>
            <option value="Praia Grande">Praia Grande</option>
            <option value="Pratania">Pratania</option>
            <option value="Presidente Alves">Presidente Alves</option>
            <option value="Presidente Bernardes">Presidente Bernardes</option>
            <option value="Presidente Epitacio">Presidente Epitacio</option>
            <option value="Presidente Prudente">Presidente Prudente</option>
            <option value="Presidente Venceslau">Presidente Venceslau</option>
            <option value="Promissao">Promissao</option>
            <option value="Quadra">Quadra</option>
            <option value="Quata">Quata</option>
            <option value="Queiroz">Queiroz</option>
            <option value="Queluz">Queluz</option>
            <option value="Quintana">Quintana</option>
            <option value="Rafard">Rafard</option>
            <option value="Rancharia">Rancharia</option>
            <option value="Redencao da Serra">Redencao da Serra</option>
            <option value="Regente Feijo">Regente Feijo</option>
            <option value="Reginopolis">Reginopolis</option>
            <option value="Registro">Registro</option>
            <option value="Restinga">Restinga</option>
            <option value="Ribeira">Ribeira</option>
            <option value="Ribeirao Bonito">Ribeirao Bonito</option>
            <option value="Ribeirao Branco">Ribeirao Branco</option>
            <option value="Ribeirao Corrente">Ribeirao Corrente</option>
            <option value="Ribeirao Grande">Ribeirao Grande</option>
            <option value="Ribeirao Pires">Ribeirao Pires</option>
            <option value="Ribeirao Preto">Ribeirao Preto</option>
            <option value="Ribeirao do Sul">Ribeirao do Sul</option>
            <option value="Ribeirao dos Indios">Ribeirao dos Indios</option>
            <option value="Rifaina">Rifaina</option>
            <option value="Rincao">Rincao</option>
            <option value="Rinopolis">Rinopolis</option>
            <option value="Rio Claro">Rio Claro</option>
            <option value="Rio Grande da Serra">Rio Grande da Serra</option>
            <option value="Rio das Pedras">Rio das Pedras</option>
            <option value="Riolandia">Riolandia</option>
            <option value="Riversul">Riversul</option>
            <option value="Rosana">Rosana</option>
            <option value="Roseira">Roseira</option>
            <option value="Rubiacea">Rubiacea</option>
            <option value="Rubineia">Rubineia</option>
            <option value="Sabino">Sabino</option>
            <option value="Sagres">Sagres</option>
            <option value="Sales Oliveira">Sales Oliveira</option>
            <option value="Sales">Sales</option>
            <option value="Salesopolis">Salesopolis</option>
            <option value="Salmourao">Salmourao</option>
            <option value="Saltinho">Saltinho</option>
            <option value="Salto Grande">Salto Grande</option>
            <option value="Salto de Pirapora">Salto de Pirapora</option>
            <option value="Salto">Salto</option>
            <option value="Sandovalina">Sandovalina</option>
            <option value="Santa Adelia">Santa Adelia</option>
            <option value="Santa Albertina">Santa Albertina</option>
            <option value="Santa Barbara d'Oeste">Santa Barbara d'Oeste</option>
            <option value="Santa Branca">Santa Branca</option>
            <option value="Santa Clara d'Oeste">Santa Clara d'Oeste</option>
            <option value="Santa Cruz da Conceicao">Santa Cruz da Conceicao</option>
            <option value="Santa Cruz da Esperanca">Santa Cruz da Esperanca</option>
            <option value="Santa Cruz das Palmeiras">Santa Cruz das Palmeiras</option>
            <option value="Santa Cruz do Rio Pardo">Santa Cruz do Rio Pardo</option>
            <option value="Santa Ernestina">Santa Ernestina</option>
            <option value="Santa Fe do Sul">Santa Fe do Sul</option>
            <option value="Santa Gertrudes">Santa Gertrudes</option>
            <option value="Santa Isabel">Santa Isabel</option>
            <option value="Santa Lucia">Santa Lucia</option>
            <option value="Santa Maria da Serra">Santa Maria da Serra</option>
            <option value="Santa Mercedes">Santa Mercedes</option>
            <option value="Santa Rita d'Oeste">Santa Rita d'Oeste</option>
            <option value="Santa Rita do Passa Quatro">Santa Rita do Passa Quatro</option>
            <option value="Santa Rosa de Viterbo">Santa Rosa de Viterbo</option>
            <option value="Santa Salete">Santa Salete</option>
            <option value="Santana da Ponte Pensa">Santana da Ponte Pensa</option>
            <option value="Santana de Parnaiba">Santana de Parnaiba</option>
            <option value="Santo Anastacio">Santo Anastacio</option>
            <option value="Santo Andre">Santo Andre</option>
            <option value="Santo Antonio da Alegria">Santo Antonio da Alegria</option>
            <option value="Santo Antonio de Posse">Santo Antonio de Posse</option>
            <option value="Santo Antonio do Aracangua">Santo Antonio do Aracangua</option>
            <option value="Santo Antonio do Jardim">Santo Antonio do Jardim</option>
            <option value="Santo Antonio do Pinhal">Santo Antonio do Pinhal</option>
            <option value="Santo Expedito">Santo Expedito</option>
            <option value="Santopolis do Aguapei">Santopolis do Aguapei</option>
            <option value="Santos">Santos</option>
            <option value="Sao Bento do Sapucai">Sao Bento do Sapucai</option>
            <option value="Sao Bernardo do Campo">Sao Bernardo do Campo</option>
            <option value="Sao Caetano do Sul">Sao Caetano do Sul</option>
            <option value="Sao Carlos">Sao Carlos</option>
            <option value="Sao Francisco">Sao Francisco</option>
            <option value="Sao Joao da Boa Vista">Sao Joao da Boa Vista</option>
            <option value="Sao Joao das Duas Pontes">Sao Joao das Duas Pontes</option>
            <option value="Sao Joao de Iracema">Sao Joao de Iracema</option>
            <option value="Sao Joao do Pau d'Alho">Sao Joao do Pau d'Alho</option>
            <option value="Sao Joaquim da Barra">Sao Joaquim da Barra</option>
            <option value="Sao Jose da Bela Vista">Sao Jose da Bela Vista</option>
            <option value="Sao Jose do Barreiro">Sao Jose do Barreiro</option>
            <option value="Sao Jose do Rio Pardo">Sao Jose do Rio Pardo</option>
            <option value="Sao Jose do Rio Preto">Sao Jose do Rio Preto</option>
            <option value="Sao Jose dos Campos">Sao Jose dos Campos</option>
            <option value="Sao Lourenco da Serra">Sao Lourenco da Serra</option>
            <option value="Sao Luis do Paraitinga">Sao Luis do Paraitinga</option>
            <option value="Sao Manuel">Sao Manuel</option>
            <option value="Sao Miguel Arcanjo">Sao Miguel Arcanjo</option>
            <option value="Sao Paulo">Sao Paulo</option>
            <option value="Sao Pedro do Turvo">Sao Pedro do Turvo</option>
            <option value="Sao Pedro">Sao Pedro</option>
            <option value="Sao Roque">Sao Roque</option>
            <option value="Sao Sebastiao da Grama">Sao Sebastiao da Grama</option>
            <option value="Sao Sebastiao">Sao Sebastiao</option>
            <option value="Sao Simao">Sao Simao</option>
            <option value="Sao Vicente">Sao Vicente</option>
            <option value="Sarapui">Sarapui</option>
            <option value="Sarutaia">Sarutaia</option>
            <option value="Sebastianopolis do Sul">Sebastianopolis do Sul</option>
            <option value="Serra Azul">Serra Azul</option>
            <option value="Serra Negra">Serra Negra</option>
            <option value="Serrana">Serrana</option>
            <option value="Sertaozinho">Sertaozinho</option>
            <option value="Sete Barras">Sete Barras</option>
            <option value="Severinia">Severinia</option>
            <option value="Silveiras">Silveiras</option>
            <option value="Socorro">Socorro</option>
            <option value="Sorocaba">Sorocaba</option>
            <option value="Sud Mennucci">Sud Mennucci</option>
            <option value="Sumare">Sumare</option>
            <option value="Suzanapolis">Suzanapolis</option>
            <option value="Suzano">Suzano</option>
            <option value="Tabapua">Tabapua</option>
            <option value="Tabatinga">Tabatinga</option>
            <option value="Taboao da Serra">Taboao da Serra</option>
            <option value="Taciba">Taciba</option>
            <option value="Taguai">Taguai</option>
            <option value="Taiacu">Taiacu</option>
            <option value="Taiuva">Taiuva</option>
            <option value="Tambau">Tambau</option>
            <option value="Tanabi">Tanabi</option>
            <option value="Tapirai">Tapirai</option>
            <option value="Tapiratiba">Tapiratiba</option>
            <option value="Taquaral">Taquaral</option>
            <option value="Taquaritinga">Taquaritinga</option>
            <option value="Taquarituba">Taquarituba</option>
            <option value="Taquarivai">Taquarivai</option>
            <option value="Tarabai">Tarabai</option>
            <option value="Taruma">Taruma</option>
            <option value="Tatui">Tatui</option>
            <option value="Taubate">Taubate</option>
            <option value="Tejupa">Tejupa</option>
            <option value="Teodoro Sampaio">Teodoro Sampaio</option>
            <option value="Terra Roxa">Terra Roxa</option>
            <option value="Tiete">Tiete</option>
            <option value="Timburi">Timburi</option>
            <option value="Torre de Pedra">Torre de Pedra</option>
            <option value="Torrinha">Torrinha</option>
            <option value="Trabiju">Trabiju</option>
            <option value="Tremembe">Tremembe</option>
            <option value="Tres Fronteiras">Tres Fronteiras</option>
            <option value="Tuiuti">Tuiuti</option>
            <option value="Tupa">Tupa</option>
            <option value="Tupi Paulista">Tupi Paulista</option>
            <option value="Turiuba">Turiuba</option>
            <option value="Turmalina">Turmalina</option>
            <option value="Ubarana">Ubarana</option>
            <option value="Ubatuba">Ubatuba</option>
            <option value="Ubirajara">Ubirajara</option>
            <option value="Uchoa">Uchoa</option>
            <option value="Uniao Paulista">Uniao Paulista</option>
            <option value="Urania">Urania</option>
            <option value="Uru">Uru</option>
            <option value="Urupes">Urupes</option>
            <option value="Valentim Gentil">Valentim Gentil</option>
            <option value="Valinhos">Valinhos</option>
            <option value="Valparaiso">Valparaiso</option>
            <option value="Vargem Grande Paulista">Vargem Grande Paulista</option>
            <option value="Vargem Grande do Sul">Vargem Grande do Sul</option>
            <option value="Vargem">Vargem</option>
            <option value="Varzea Paulista">Varzea Paulista</option>
            <option value="Vera Cruz">Vera Cruz</option>
            <option value="Vinhedo">Vinhedo</option>
            <option value="Viradouro">Viradouro</option>
            <option value="Vista Alegre do Alto">Vista Alegre do Alto</option>
            <option value="Vitoria Brasil">Vitoria Brasil</option>
            <option value="Votorantim">Votorantim</option>
            <option value="Votuporanga">Votuporanga</option>
            <option value="Zacarias">Zacarias</option>
          </select>
        </div>

        <button>Cadastrar</button>
      </form>
    );
  }
}

export default SignupForm;
